#pragma once

#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME "Waite Design Labs"
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME "TinyENV Sensor"
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING "0.5.2"
#define CHIP_DEVICE_CONFIG_DEFAULT_DEVICE_HARDWARE_VERSION_STRING "1.1"
