#pragma once

#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME "c3474"
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME "Garden Sensor"
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING "1.0.0"
#define CHIP_DEVICE_CONFIG_DEVICE_HARDWARE_VERSION_STRING "1.0"
